name: 'Run tests on Bun'

on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/**'
    - '.eslintrc.cjs'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  pull_request:
    branches:
    - 'main'
    paths:
    - '.github/**'
    - '.eslintrc.cjs'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 8

    - uses: actions/cache@v4
      name: Setup dependency cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-bun-store-

    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install --frozen-lockfile --strict-peer-dependencies

    - name: Lint Source
      run: bun run --if-present lint

    - name: Build Source
      run: bun run --if-present build

    - name: Run Tests
      run: bun run --if-present test
