name: 'Run tests on Deno'

on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/**'
    - '.eslintrc.cjs'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  pull_request:
    branches:
    - 'main'
    paths:
    - '.github/**'
    - '.eslintrc.cjs'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 8

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - uses: actions/cache@v4
      name: Setup dependency cache
      with:
        path: |
          ~/.cache/deno
          ~/.deno/bin
          ~/.deno/gen
          ~/.deno/deps
        key: ${{ runner.os }}-deno-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
            ${{ runner.os }}-deno-store-

    - name: Lint Source
      run: deno lint --ignore=node_modules **/*.ts

    - name: Run Tests
      run: deno run --allow-all --unstable-sloppy-imports npm:uvu tests
