name: Publish on JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        name: Set up Deno cache
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Peer Dependencies
        run: |
          deno cache npm:@expo/devcert npm:vite \
            --allow-scripts \
            --no-lock \
            --node-modules-dir=auto

      - run: |
          deno lint --ignore=node_modules **/*.ts

          deno publish --dry-run
          deno publish
