name: 'Run tests on NodeJS'

on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/workflows/node.yml'
    - 'biome.jsonc'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  pull_request:
    branches:
    - 'main'
    paths:
    - '.github/workflows/node.yml'
    - 'biome.jsonc'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'src/**'
    - 'tests/**'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['lts/*', '*']

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 10

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: Lint Source
      run: pnpm exec biome ci

    - name: Build Source
      run: pnpm run --if-present build

    - name: Run Tests
      run: pnpm run --if-present test
